[book]
src = "src"
title = "Teller Protocol"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/teller-protocol/teller-protocol-v2"

[output.html.fold]
enable = true
